Feature 53
platzily/platzily-ui pull request #79
Opened 2021-11-17 22:14 UTC by danielvaldivv

## Checklist ✅

- [x] I have followed the [contributor guideline](https://github.com/platzily/platzily-ui/blob/master/CONTRIBUTING.md)
- [x] Tests are included
- [x] Documentation is changed or added
- [x] Related issue has been created
- [x] Commits messages follows [commit guideline](https://github.com/platzily/platzily-ui/blob/master/CONTRIBUTING.md/#Commits)

resolves [# 53]

2021-11-18 03:00 UTC, KevFarid commented
You remember adding the info to Side Bar as: Reviewers, assigners, Labels, Projects, Milestone and Issue. too, add screenshot of the component in the PR.
Additional: My personal recommendation is to name the PR with the Issue Name, example: Feature 53 - Footer Component

2021-11-20 00:13 UTC, kevfarid commented on packages/components/src/Footer/Footer.js
> +      position,
Remove the position prop, not is necessary. I already talked about this to @omarefg.

2021-11-23 15:53 UTC, omarefg requested changes

2021-11-23 15:53 UTC, omarefg commented on packages/components/src/Footer/Footer.js
> +      position,
I agree with this. We should let the position as default by the element, if the user wants to change it, can be done using the useStyleSheet hook.

2021-11-23 15:53 UTC, omarefg commented on packages/components/src/Footer/Footer.js
> +  { key: 'footerWrapper' },
can we change this to `footer` instead?

2021-11-23 15:53 UTC, omarefg commented on packages/components/src/Footer/Footer.js
> +  position: PropTypes.oneOf(['static', 'relative', 'absolute', 'fixed', 'sticky', 'unset']),
This can be removed too, as mentioned in https://github.com/platzily/platzily-ui/pull/79/files#r751863930

2021-11-23 15:53 UTC, omarefg commented on packages/components/src/Footer/Footer.js
> +Footer.defaultProps = {
This can be removed too, as mentioned in https://github.com/platzily/platzily-ui/pull/79/files#r751863930

2021-11-23 15:53 UTC, omarefg commented on packages/components/src/Footer/Footer.spec.js
> +  it('Given the Footer Component, when the props provide position attribute then the component will take those style', () => {
This test can be removed too, as mentioned in https://github.com/platzily/platzily-ui/pull/79/files#r751863930 :grin:

2021-11-23 15:53 UTC, omarefg commented on packages/docs/components/Footer/Footer.js
> +  const headerStyle = {
Lets use the useStyleSheet instead

2021-11-23 15:53 UTC, omarefg commented on packages/docs/pages/components/Footer.mdx
> +This component will provide you the Footer wrapper.
`This component will provide you the Platzily-UI Footer`

2021-11-23 15:53 UTC, omarefg commented on packages/docs/pages/components/Footer.mdx
> +It will be possible to provide 2 styles by props. These can be bgColor or position.
Just bgColor :grin:

2021-11-23 15:53 UTC, omarefg commented on packages/docs/pages/components/Footer.mdx
> +    <Footer style={{ display: flex }}>
This is not a good practice, lets remove this example.

2021-11-23 15:53 UTC, omarefg commented on packages/docs/pages/components/Footer.mdx
> +If you want to provide many props, is possible to create an object and provide the object inside the style attribute.
We could encourage the use of the useStyleSheet hook instead :grin:

2021-11-23 15:53 UTC, omarefg commented on packages/docs/pages/components/Footer.mdx
> +The best way to create styles is using createStyleSheet method.
Oh I see it's here, lets remove the two examples above. This one should be enough.

2021-11-27 14:44 UTC, omarefg approved these changes

2021-12-07 00:56 UTC, merged