Feature 71
platzily/platzily-ui pull request #83
Opened 2021-11-27 15:42 UTC by omarefg

## Checklist ✅

- [x] I have followed the [contributor guideline](https://github.com/platzily/platzily-ui/blob/master/CONTRIBUTING.md)
- [x] Tests are included
- [x] Documentation is changed or added
- [x] Related issue has been created
- [x] Commits messages follows [commit guideline](https://github.com/platzily/platzily-ui/blob/master/CONTRIBUTING.md/#Commits)

resolves #71

2021-11-27 15:46 UTC, KevFarid commented
Please, add name of issue to PR. Example: Feature 71 - useWindowDimensions

2021-11-27 15:48 UTC, omarefg commented
> Please, add name of issue to PR. Example: Feature 71 - useWindowDimensions

Done :heavy_check_mark:

2021-11-27 16:14 UTC, KevFarid approved these changes

2021-11-27 16:14 UTC, KevFarid commented on .eslintrc.js
> +    'no-restricted-exports': 'off'
Can you use overrides to turn off this rule?

2021-11-27 21:55 UTC, KevFarid requested changes

2021-11-27 21:55 UTC, KevFarid commented on .eslintrc.js
> +    'no-restricted-exports': 'off'
Can you use overrides to turn off this rule?

2021-11-30 03:53 UTC, KevFarid approved these changes

2021-11-30 16:54 UTC, merged